name: t2_topicos
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - jupyterlab
  - pip
  - pip:
      - ydata-profiling
      - black
      - coloredlogs
      - matplotlib
      - notebook
      - numpy
      - pandas
      - seaborn
      - typeguard
      - scikit-learn